# Put these settings in the apache system config httpd.conf file
# Replace "/<site-path>/<domain-name>/" on lines 12-13 below according to your site's installation path

# Remove the # sign below for centos/rockylinux/almalinux users
# LoadModule xsendfile_module /usr/lib64/httpd/modules/mod_xsendfile.so

# Remove the # sign below for debian/ubuntu users
# LoadModule xsendfile_module /usr/lib/apache2/modules/mod_xsendfile.so

<IfModule mod_xsendfile.c>
    XSendFile on
    # XSendFilePath "/<site-path>/<domain-name>/cache/files"
    # XSendFilePath "/<site-path>/<domain-name>/public/uploads"
</IfModule>