export type HostingData = Readonly<{
  hostnames: Readonly<Record<string, readonly string[]>>
  downloadUrls: Readonly<Record<string, string>>
}>

export const legacyHostingData: HostingData = Object.freeze({
  hostnames: Object.freeze({
    vidara: [],
    nossoplayer: ['nossoplayeronlinehd.'],
    embedtv2: ['embedtv.'],
    embedtv: ['embedtv-3.', 'embedtv-4.'],
    savefiles: ['streamhls.'],
    thetube: [],
    amazon: [],
    aparat: [],
    archive: [],
    blogger: ['blogspot.'],
    cloudmailru: ['cloud.mail.'],
    cyberfile: [],
    dailymotion: ['dailymotion.', 'geo.dailymotion.'],
    direct: [],
    dood: ['d0000d.', 'd000d.', 'dood.', 'doods.', 'doodstream.', 'ds2video.', 'playmogo.'],
    dropbox: [],
    dropload: ['dr0pstream.'],
    dzen: ['cdn.dzen.'],
    facebook: [],
    filemail: [],
    filemoon: ['fmoonembed.'],
    filesfm: [],
    fileupload: ['file-upload.'],
    fireload: [],
    firevideoplayer: ['basseqwevewcewcewecwcw.', 'embedder.', 'embedplayer.', 'firevideoplayer.', 'superflixapi.'],
    gdrive: ['drive.google.', 'googleapis.'],
    gofile: [],
    goodstream: ['goodstream.one', 'goodstream1.one'],
    googlephotos: ['photos.app.goo.', 'photos.google.'],
    hexupload: ['hexload.'],
    hxfile: [],
    iceyfile: [],
    krakenfiles: [],
    lulustream: ['lulu.', 'luluvdo.', 'luluvdoo.', 'luluvid.'],
    mediacm: ['media.cm'],
    mediafire: [],
    mixdrop: [],
    mp4upload: [],
    mstream: ['sharepoint.'],
    mymailru: ['my.mail.ru'],
    navertv: ['tv.naver.'],
    okru: ['odnoklassniki.', 'ok.ru'],
    pcloud: [],
    pixeldrain: [],
    rumble: [],
    sendvid: [],
    sibnet: [],
    soundcloud: [],
    streama2z: [],
    streamable: [],
    streamtape: ['adblockplustape.', 'stapadblockuser.', 'strcloud.', 'streamadblocker.', 'streamadblockplus.', 'streamta.', 'streamtape.', 'streamtapeadblockuser.', 'strtape.', 'strtpe.', 'tapeadvertisement.'],
    streamhg: ['hgcloud.', 'masukestin.', 'audinifer.', 'vibuxer.', 'ghbrisk.', 'embedwish.', 'cybervynx.', 'hlsflex.', 'asnwish.', 'flaswish.', 'iplayerhls.', 'jodwish.', 'jwplayerhls.', 'playerwish.', 'streamhg.', 'streamwish.', 'strwish.', 'swdyu.', 'wishfast.', 'wishonly.', 'dhcplay.', 'swiftplayers.', 'extrhg.', 'tryzendm.', 'hglink.', 'davioad.', 'dumbalag.'],
    supervideo: [],
    tiktok: [],
    turboviplay: ['emturbovid.', 'stbturbo.', 'turbovidhls.'],
    twitch: [],
    udrop: [],
    uqload: [],
    earnvids: ['filelions.', 'earnvids.', 'vidhide.', 'vidhidefast.', 'vidhideplus.', 'vidhidepre.', 'vidhidepro.', 'vidhidevip.', 'smoothpre.', 'movearnpre.'],
    vidmoly: [],
    vidoza: ['videzz.'],
    vidtube: [],
    vidyard: [],
    vimeo: [],
    vk: ['vkvideo.'],
    voe: ['boonlessbestselling244.', 'josephseveralconcern.', 'phenomenalityuniform.'],
    vtube: ['vtbe.', 'vtplay.'],
    vudeo: [],
    wetransfer: ['we.', 'wetransfer.'],
    yadisk: ['yadi.', 'yandex.'],
    yourupload: [],
    youtube: ['youtu.'],
    ytdlp: []
  }),
  downloadUrls: Object.freeze({
    direct: '%s', blogger: 'https://www.blogger.com/video.g?token=%s', vidara: 'https://vidara.to/v/%s',
    savefiles: 'https://streamhls.to/%s', thetube: 'https://the.tube/%s', amazon: 'https://www.amazon.com/clouddrive/share/%s',
    aparat: 'https://www.aparat.com/v/%s', archive: 'https://archive.org/details/%s', cloudmailru: 'https://cloud.mail.ru/%s',
    cyberfile: 'https://cyberfile.me/%s', dailymotion: 'https://www.dailymotion.com/video/%s', dood: 'https://doodstream.com/e/%s',
    dropbox: 'https://www.dropbox.com/s/%s', dropload: 'https://dropload.io/%s', dzen: 'https://dzen.ru/embed/%s',
    facebook: 'https://www.facebook.com/%s', filemail: 'https://www.filemail.com/d/%s', filemoon: 'https://filemoon.to/d/%s',
    fileupload: 'https://www.file-upload.org/%s', fireload: 'https://www.fireload.com/%s', gdrive: 'https://drive.google.com/file/d/%s/view',
    gofile: 'https://gofile.io/d/%s', goodstream: 'https://goodstream.one/%s', googlephotos: 'https://photos.google.com/%s',
    hexupload: 'https://hexload.com/%s', hxfile: 'https://hxfile.co/%s', iceyfile: 'https://iceyfile.com/%s',
    krakenfiles: 'https://krakenfiles.com/view/%s/file.html', lulustream: 'https://lulustream.com/d/%s', mediacm: 'https://media.cm/%s',
    mediafire: 'https://www.mediafire.com/file/%s', mixdrop: 'https://mixdrop.ag/f/%s', mp4upload: 'https://www.mp4upload.com/%s',
    mymailru: 'https://my.mail.ru/video/embed/%s', navertv: 'https://tv.naver.com/%s', okru: 'https://ok.ru/video/%s',
    pixeldrain: 'https://pixeldrain.com/u/%s', rumble: 'https://rumble.com/%s', sendvid: 'https://sendvid.com/%s',
    sibnet: 'https://video.sibnet.ru/%s', streama2z: 'https://streama2z.com/%s', streamable: 'https://streamable.com/%s',
    streamtape: 'https://tapeadvertisement.com/e/%s', streamvid: 'https://streamvid.net/%s', streamhg: 'https://hglink.to/%s',
    supervideo: 'https://supervideo.cc/%s', tiktok: 'https://www.tiktok.com/%s', turboviplay: 'https://emturbovid.com/t/%s',
    udrop: 'https://www.udrop.com/%s', uqload: 'https://uqload.ws/%s', earnvids: 'https://movearnpre.com/file/%s',
    vidmoly: 'https://vidmoly.me/v/%s', vidoza: 'https://videzz.net/%s', vidtube: 'https://vidtube.one/%s',
    vidyard: 'https://share.vidyard.com/watch/%s', vimeo: 'https://vimeo.com/%s', vk: 'https://vk.com/%s',
    voe: 'https://voe.sx/%s', vtube: 'https://vtube.network/%s', vudeo: 'https://vudeo.ws/%s',
    yadisk: 'https://yadi.sk/i/%s', yourupload: 'https://yourupload.com/watch/%s', youtube: 'https://youtube.com/watch?v=%s',
    embedtv: 'https://embedtv-3.icu/%s', embedtv2: 'https://www.embedtv.net/embed/%s', nossoplayer: 'https://nossoplayeronlinehd.org/tv/%s'
  })
})
