const SMART_TV_KEYWORDS = Object.freeze([
  'smarttv',
  'smart-tv',
  'smart_tv',
  'tv',
  'hbbtv',
  'ce-html',
  'inettvbrowser',
  'opera tv',
  'netrangemmh',
  'web0s',
  'maple',
  'espial',
  'midp',
  'webostv',
  'webos',
  'netcast',
  'lg browser',
  'samsung',
  'samsung tv',
  'tizen',
  'sonydtv',
  'sony tv',
  'bravia',
  'viera',
  'nettv',
  'aquos',
  'toshiba dtv',
  'dtv',
  'hisense',
  'vidaa',
  'tcl',
  'vizio',
  'smartcast',
  'roku',
  'appletv',
  'tvos',
  'android tv',
  'shield android tv',
  'atv',
  'aft',
  'chromecast',
  'crkey',
  'xbox one',
  'xbox series',
  'playstation 4',
  'playstation 5',
  'kded',
  'h96',
  'freebox',
  'wii',
  'playstation',
  'nintendo',
  'xbox',
  'seraphic',
  'sraf',
  'tpm171e',
  'a95x-r1',
  'netbox',
  'mxqpro',
  'tx3',
  'm8s',
  'neo-u1',
  't95zplus',
  'beelink',
  'abox',
  'v88',
  'zidoo',
  'brightsign',
  'mitv',
  'leelbox',
  'minia5x',
  'mobile vr',
  'directfb',
  'kylo',
  'ppc',
  'telefunken'
])

const SMART_TV_PATTERNS = Object.freeze([
  /smart[-_]tv/i,
  /\bx96(?:mini)?\b/i,
  /\bmx(?:9|iii)\b/i,
  /linux\s+(?:sh4|mips)/i,
  /\b(?:aftb|afts|aftm|aftt)\b/i,
  /\b(?:ps4|ps5)\b/i
])

/** Reproduces the legacy Smart TV keyword and media-box delivery exemption. */
export function isSmartTvUserAgent(userAgent: string): boolean {
  const normalized = userAgent.trim().slice(0, 1_024).toLowerCase()
  if (normalized === '') return false
  return SMART_TV_KEYWORDS.some((keyword) => normalized.includes(keyword)) ||
    SMART_TV_PATTERNS.some((pattern) => pattern.test(normalized))
}
